ONLY = ["id", "email"]
EXCLUDE = ["password_hash"]
EXPIRES_IN = 360_000_000
UNASSIGNED = "unassigned"
ADMIN = 'admin'
COMPANY = 'company'
EMPLOYEE = 'employee'
DRIVER = 'driver'
LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
