ONLY = ["id", "email"]
EXCLUDE = ["password_hash"]
EXPIRES_IN = 360_000_000
UNASSIGNED = "unassigned"
ADMIN = 'admin'
EMPLOYEE = 'employee'
SECRETARY = 'secretary'
DRIVER = 'driver'
# LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
HEAD_SECRETARY = 'head_secretary'
