"""third

Revision ID: 1198ee6c2c84
Revises: ff1f071bb8e5
Create Date: 2019-05-30 00:59:08.061406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1198ee6c2c84'
down_revision = 'ff1f071bb8e5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'date')
    # ### end Alembic commands ###
