"""third

Revision ID: 2175f4646f6c
Revises: 4bf4110636be
Create Date: 2019-05-31 14:48:10.885014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2175f4646f6c'
down_revision = '4bf4110636be'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_reservation',
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_reservation')
    # ### end Alembic commands ###
