"""reservation.code renamed to reservation.name

Revision ID: 41e99efa8d68
Revises: b92aa20fb5b8
Create Date: 2019-06-13 12:36:51.039224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e99efa8d68'
down_revision = 'b92aa20fb5b8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'code', new_column_name="name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'name', new_column_name="code")
    # ### end Alembic commands ###
