"""second

Revision ID: 471a65ab5aad
Revises: 635cd13f30e2
Create Date: 2019-05-26 23:26:26.742538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '471a65ab5aad'
down_revision = '635cd13f30e2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('pickup', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('due', sa.Date(), nullable=True),
    sa.Column('from_business_name', sa.String(), nullable=True),
    sa.Column('from_addressline_1', sa.String(), nullable=True),
    sa.Column('from_addressline_2', sa.String(), nullable=True),
    sa.Column('from_city', sa.String(), nullable=True),
    sa.Column('from_postcode', sa.String(), nullable=True),
    sa.Column('to_client_name', sa.String(), nullable=True),
    sa.Column('to_addressline_1', sa.String(), nullable=True),
    sa.Column('to_addressline_2', sa.String(), nullable=True),
    sa.Column('to_city', sa.String(), nullable=True),
    sa.Column('to_postcode', sa.String(), nullable=True),
    sa.Column('payment_account_name', sa.String(), nullable=True),
    sa.Column('payment_account_sortcode', sa.String(), nullable=True),
    sa.Column('payment_account_number', sa.String(), nullable=True),
    sa.Column('invoice_notes', sa.Text(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('discount', sa.String(), nullable=True),
    sa.Column('tax', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drivers', sa.Column('status', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('address', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'companys', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'company_id')
    op.drop_column('employees', 'address')
    op.drop_column('drivers', 'status')
    op.drop_table('items')
    op.drop_table('invoices')
    op.drop_table('reservations')
    # ### end Alembic commands ###
