"""second

Revision ID: 4bf4110636be
Revises: 8f1b69c39fd7
Create Date: 2019-05-30 22:13:58.845166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf4110636be'
down_revision = '8f1b69c39fd7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('discount', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'discount')
    # ### end Alembic commands ###
