"""second

Revision ID: 5c97d2419921
Revises: ee3d6daa2beb
Create Date: 2019-05-30 00:05:44.353223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c97d2419921'
down_revision = 'ee3d6daa2beb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('time', sa.Time(), nullable=True))
    op.alter_column('reservations', 'datetime', new_column_name="date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'date', new_column_name="datetime")
    op.drop_column('reservations', 'time')
    # ### end Alembic commands ###
