"""second

Revision ID: 9165e18ce33e
Revises: c3eb8735a948
Create Date: 2019-06-08 03:20:43.634300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9165e18ce33e'
down_revision = 'c3eb8735a948'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companys', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companys', 'code')
    # ### end Alembic commands ###
