"""second

Revision ID: c3eb8735a948
Revises: 41dc3b18e87e
Create Date: 2019-06-07 23:35:15.342146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3eb8735a948'
down_revision = '41dc3b18e87e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('stops', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stops', 'time')
    op.drop_column('stops', 'date')
    # ### end Alembic commands ###
