"""second

Revision ID: ff1f071bb8e5
Revises: 5c97d2419921
Create Date: 2019-05-30 00:58:20.291725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1f071bb8e5'
down_revision = '5c97d2419921'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('from_phone', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('from_vat', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('to_phone', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('to_vat', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'to_vat')
    op.drop_column('invoices', 'to_phone')
    op.drop_column('invoices', 'from_vat')
    op.drop_column('invoices', 'from_phone')
    # ### end Alembic commands ###
